This documentation contains information used by myself (JonasPammer)
to maintain all the repos.

== all-repos

https://github.com/asottile/all-repos[all-repos] is a project by asotille
to clone multiple repositories and apply sweeping changes at once.

link:all-repos-in.json[] is an `all.repos.source.json_file` compatible file
consisting of all of my ansible roles.
It can be used in an all-repos configuration file as shown in `link:all-repos.example.json[]`:

.all-repos.json
[source%linenums,json,highlight=3..5]
----
include::all-repos.example.json[]
----


== Commands

.step 1: initially configure `all-repos`
[subs="quotes"]
----
~/dev$ *git clone git@github.com:JonasPammer/ansible-roles.git*

~/dev$ *cd ansible-roles*

~/dev/ansible-roles$ *_python3 -m venv venv_*

~/dev/ansible-roles$ *_source venv/bin/activate_*

#(venv)# ~/dev/ansible-roles$ *pip3 install -e .*

#(venv)# ~/dev/ansible-roles$ *pip3 install -r requirements-dev.txt*

(venv) ~/dev/ansible-roles$ *cp all-repos.example.json all-repos.json*

(venv) ~/dev/ansible-roles$ *nano all-repos.json*
...(fill in 'EDIT_ME' placeholders)...

(venv) ~/dev/ansible-roles$ *chmod 600 all-repos.json*
----

.step 2: clone (execute this command before any maintenance command)
[subs="quotes"]
----
(venv) ~/dev/ansible-roles$ *all-repos-clone*
----

.step 3: configure a GITHUB_TOKEN
====
Some Scripts require an appropriately permissioned github token,
sourced it from the environment variable `GITHUB_TOKEN` or
a local gitignore'd `.env` file.

1. Go to https://github.com/settings/tokens/new
2. Add your note (e.g. `ansible-roles mylaptop`)
   and select your preferred expiration date
3. Select the required (most-often just `public_repo`)
4. Generate, Copy and paste the token into your local `.env` file
   (must be located at the root of the projects' directory)
+
[source,dotenv]
----
GITHUB_TOKEN=LoremipsumLoremipsumLoremipsumLoremipsum
----
====

.example maintenance: cruft update / pre-commit run all
====
[subs="quotes"]
----
(venv) ~/dev/ansible-roles$ *ansible-roles-cruft*
----
====

.example maintenance: merge all pre-commit.ci / dependabot pull requests
====
[subs="quotes"]
----
(venv) ~/dev/ansible-roles$ *ansible-roles-merge_bot_pull_requests*
----
====

.example maintenance: ensure minimum supported ansible version is correct
====
$ all-repos-sed --commit-msg "chore: set min_ansible_version to 2.11 as per JonasPammer/cookiecutter-ansible-roles" \
     's/min_ansible_version: ".*"/min_ansible_version: "2.11"/g' \
     meta/main.yml
$ all-repos-sed --commit-msg "chore: set min_ansible_version to 2.11 as per JonasPammer/cookiecutter-ansible-roles" \
     's/min_ansible_version": ".*"/min_ansible_version": "2.11"/g' \
     .cruft.json
====

.example maintenance: update GitHub Secret `GALAXY_API_KEY`
====
[subs="quotes"]
----
(venv) ~/dev/ansible-roles$ *ansible-roles-sync_meta --galaxy*
----
====
