= JonasPammer's Ansible roles
Jonas Pammer <opensource@jonaspammer.at>;
GitHub Actions <>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


_https://jonaspammer.github.io/ansible-roles[This page]
is being periodically re-generated by a GitHub Action._

toc::[]

== Ansible Roles

|===
| Role name | Action Status | Version | Open Issues | Open Pull Requests


| https://github.com/JonasPammer/ansible-role-bootstrap[bootstrap]
| https://github.com/JonasPammer/ansible-role-bootstrap/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-bootstrap/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-bootstrap/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-bootstrap/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-bootstrap/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-bootstrap/latest.svg[version]]
| https://github.com/JonasPammer/ansible-role-bootstrap/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-bootstrap[issues]]
| https://github.com/JonasPammer/ansible-role-bootstrap/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-bootstrap[pull requests]]

| https://github.com/JonasPammer/ansible-role-core_dependencies[core_dependencies]
| https://github.com/JonasPammer/ansible-role-core_dependencies/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-core_dependencies/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-core_dependencies/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-core_dependencies/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-core_dependencies/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-core_dependencies/latest.svg[version]]
| https://github.com/JonasPammer/ansible-role-core_dependencies/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-core_dependencies[issues]]
| https://github.com/JonasPammer/ansible-role-core_dependencies/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-core_dependencies[pull requests]]

| https://github.com/JonasPammer/ansible-role-pip[pip]
| https://github.com/JonasPammer/ansible-role-pip/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-pip/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-pip/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-pip/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-pip/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-pip/latest.svg[version]]
| https://github.com/JonasPammer/ansible-role-pip/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-pip[issues]]
| https://github.com/JonasPammer/ansible-role-pip/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-pip[pull requests]]

|===

=== Dependencies

==== Soft Dependencies
Most roles have a set of “soft dependencies” described in their `requirements.yml` file.
These soft dependencies are used in the relevant CI Tests
to prepare the machine for the execution of a given role
or to test some kind of interoperability.

You can choose to use those roles if you like them.

Here is an overview of all roles with their soft dependencies:

image:./graphs/dependencies_ALL.svg[requriements.yml soft-dependency graph of all roles]

The dependencies are soft for these reasons:

* Better re-usability.
* Easier to fork.
* *Lets the system developer assume a start-state of a machine.*

Because these dependencies are loose,
you have to include them in your playbook yourself
(assuming you want to use them):

[source,yaml]
----
- name: make the best machine ever
  hosts: all
  become: yes

  roles:
    - role: jonaspammer.bootstrap
    - role: jonaspammer.java
----

==== Hard Dependencies

Some roles have a required hard dependency on another role,
mainly for a common handler or for variables that are set in the parent role and used in the child role.
_These role dependencies
(https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-role-dependencies[official documentation])
are described in `meta/main.yml` file of a given role under `dependencies`._

|===
| Role name | Depends on | Reason














|===

Here is an overview of all hard dependencies:

image:./graphs/dependencies_ALL-hard.svg[meta/main.yml hard-dependency graph of all roles]

Because Ansible defines role dependencies as 'prerequisites' and not 'true dependencies',
you still *have to* include them in your playbook yourself:

[source,yaml]
----
- name: Converge
  hosts: all
  become: yes

  roles:
    # (preperation roles have been left out for this example)

    - role: jonaspammer.httpd
    - role: jonaspammer.php
----


=== Tested Distributions

A role may work on different *distributions*, like Red Hat Enterprise Linux (RHEL),
even though there is no test for this exact distribution.

The following Linux distributions are included in the tests of each role
https://github.com/JonasPammer/cookiecutter-ansible-role/blob/master/ansible-role-%7B%7B%20cookiecutter.role_name%20%7D%7D/.github/workflows/ci.yml[by default]:

|===
| OS Family | Distribution | Accompanying Docker Image

| Rocky
| Rocky Linux 8
| https://github.com/geerlingguy/docker-rockylinux8-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-rockylinux8-ansible/workflows/Build/badge.svg?branch=master&event=push[CI]]

| RedHat
| CentOS 7
| https://github.com/geerlingguy/docker-centos7-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-centos7-ansible/workflows/Build/badge.svg?branch=master&event=push[CI]]

| Debian
| Ubuntu 1804
| https://github.com/geerlingguy/docker-ubuntu1804-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu1804-ansible/workflows/Build/badge.svg?branch=master&event=push[CI]]

| Debian
| Ubuntu 2004
| https://github.com/geerlingguy/docker-ubuntu2004-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu2004-ansible/workflows/Build/badge.svg?branch=master&event=push[CI]]

| Debian
| Debian 10
| https://github.com/geerlingguy/docker-debian10-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian10-ansible/workflows/Build/badge.svg?branch=master&event=push[CI]]

| Debian
| Debian 11
| https://github.com/geerlingguy/docker-debian11-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian11-ansible/workflows/Build/badge.svg?branch=master&event=push[CI]]
|===

=== Tested Ansible versions

The following Ansible versions are tested in the tests of each distribution
https://github.com/JonasPammer/cookiecutter-ansible-role/blob/master/ansible-role-%7B%7B%20cookiecutter.role_name%20%7D%7D/tox.ini[by default]:

* 2.9
* 2.10
* 2.11
* 2.12


== all-repos

https://github.com/asottile/all-repos[all-repos] is a project by asotille
to clone multiple repositories and apply sweeping changes at once.

link:all-repos-in.json[] is an `all.repos.source.json_file` compatible file
consisting of all of my ansible roles.
It can be used in an all-repos configuration file as shown below:

.all-repos.json
[source%linenums,json,highlight=3..5]
----
{
    "output_dir": ".",
    "source": "all_repos.source.json_file",
    "source_settings": {
        "filename": "all-repos-in.json"
    },
    "push": "all_repos.push.github_pull_request",
    "push_settings": {
        "api_key": "...",
        "username": "..."
    }
}
----

=== Example Commands

----
$ python3 -m pip install all-repos

$ all-repos-clone

// TODO add all-repos-sed examples here
----