// This file is generated from `templates/README.adoc.jinja2` by Github CI, all local changes will be lost eventually.
= JonasPammer's Ansible roles
Jonas Pammer <opensource@jonaspammer.at>;
GitHub Actions <>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


_https://jonaspammer.github.io/ansible-roles[This page]
is being periodically re-generated by a GitHub Action._

toc::[]

== Ansible Roles

[#renovate_dashboard_issue_notice]
[NOTE]
1 Issue is always open for the Renovate Dependency Dashboard!

|===
| Role name (hover badge for description) | Action Status | Version | Open Issues <<renovate_dashboard_issue_notice,*Note>> | Open Pull Requests

| 🍪 https://github.com/JonasPammer/cookiecutter-ansible-role[cookiecutter-ansible-role]
| https://github.com/JonasPammer/cookiecutter-ansible-role/actions/workflows/ci.yml[image:https://github.com/JonasPammer/cookiecutter-ansible-role/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/cookiecutter-ansible-role/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/cookiecutter-ansible-role/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/cookiecutter-ansible-role/releases[image:https://img.shields.io/github/commits-since/JonasPammer/cookiecutter-ansible-role/latest.svg[version]]
| https://github.com/JonasPammer/cookiecutter-ansible-role/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/cookiecutter-ansible-role[issues]]
| https://github.com/JonasPammer/cookiecutter-ansible-role/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/cookiecutter-ansible-role[pull requests]]



| https://github.com/JonasPammer/ansible-role-bootstrap[bootstrap] +
https://galaxy.ansible.com/jonaspammer/bootstrap[image:https://img.shields.io/badge/galaxy-jonaspammer.bootstrap-blueviolet[Available on Galaxy,title=pass:[An ansible role for preparing a linux system to be managed by ansible. Based on robertdebock&#39;s role.]]]
| https://github.com/JonasPammer/ansible-role-bootstrap/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-bootstrap/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-bootstrap/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-bootstrap/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-bootstrap/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-bootstrap/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58153%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58153%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-bootstrap/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-bootstrap[issues]]
| https://github.com/JonasPammer/ansible-role-bootstrap/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-bootstrap[pull requests]]

| https://github.com/JonasPammer/ansible-role-core_dependencies[core_dependencies] +
https://galaxy.ansible.com/jonaspammer/core_dependencies[image:https://img.shields.io/badge/galaxy-jonaspammer.core_dependencies-blueviolet[Available on Galaxy,title=pass:[An ansible role for installing dependecies to support the Ansible core modules. Based on robertdebock&#39;s core_dependencies role.]]]
| https://github.com/JonasPammer/ansible-role-core_dependencies/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-core_dependencies/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-core_dependencies/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-core_dependencies/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-core_dependencies/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-core_dependencies/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58648%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58648%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-core_dependencies/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-core_dependencies[issues]]
| https://github.com/JonasPammer/ansible-role-core_dependencies/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-core_dependencies[pull requests]]

| https://github.com/JonasPammer/ansible-role-pip[pip] +
https://galaxy.ansible.com/jonaspammer/pip[image:https://img.shields.io/badge/galaxy-jonaspammer.pip-blueviolet[Available on Galaxy,title=pass:[An ansible role for installing the latest pip (python package installer) to the system.]]]
| https://github.com/JonasPammer/ansible-role-pip/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-pip/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-pip/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-pip/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-pip/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-pip/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58884%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58884%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-pip/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-pip[issues]]
| https://github.com/JonasPammer/ansible-role-pip/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-pip[pull requests]]

| https://github.com/JonasPammer/ansible-role-shellcheck[shellcheck] +
https://galaxy.ansible.com/jonaspammer/shellcheck[image:https://img.shields.io/badge/galaxy-jonaspammer.shellcheck-blueviolet[Available on Galaxy,title=pass:[An ansible role for installing shellcheck, a static analysis tool for shell scripts.]]]
| https://github.com/JonasPammer/ansible-role-shellcheck/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-shellcheck/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-shellcheck/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-shellcheck/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-shellcheck/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-shellcheck/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58983%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F58983%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-shellcheck/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-shellcheck[issues]]
| https://github.com/JonasPammer/ansible-role-shellcheck/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-shellcheck[pull requests]]

| https://github.com/JonasPammer/ansible-role-checkmk_server[checkmk_server] +
https://galaxy.ansible.com/jonaspammer/checkmk_server[image:https://img.shields.io/badge/galaxy-jonaspammer.checkmk_server-blueviolet[Available on Galaxy,title=pass:[An ansible role for installing CheckMK RAW edition, setting up an initial site and configuring vital parameters of that site. Based on kro512&#39; checkmk_server role.]]]
| https://github.com/JonasPammer/ansible-role-checkmk_server/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-checkmk_server/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-checkmk_server/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-checkmk_server/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-checkmk_server/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-checkmk_server/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59167%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59167%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-checkmk_server/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-checkmk_server[issues]]
| https://github.com/JonasPammer/ansible-role-checkmk_server/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-checkmk_server[pull requests]]

| https://github.com/JonasPammer/ansible-role-checkmk_agent[checkmk_agent] +
https://galaxy.ansible.com/jonaspammer/checkmk_agent[image:https://img.shields.io/badge/galaxy-jonaspammer.checkmk_agent-blueviolet[Available on Galaxy,title=pass:[An Ansible role for installing checkmk&#39;s agent on a Host (Linux and Windows) by using a standard installation package.]]]
| https://github.com/JonasPammer/ansible-role-checkmk_agent/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-checkmk_agent/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-checkmk_agent/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-checkmk_agent/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-checkmk_agent/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-checkmk_agent/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59506%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59506%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-checkmk_agent/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-checkmk_agent[issues]]
| https://github.com/JonasPammer/ansible-role-checkmk_agent/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-checkmk_agent[pull requests]]

| https://github.com/JonasPammer/ansible-role-motd[motd] +
https://galaxy.ansible.com/jonaspammer/motd[image:https://img.shields.io/badge/galaxy-jonaspammer.motd-blueviolet[Available on Galaxy,title=pass:[An ansible role for configuring either static (traditional) or dynamic (using `update-motd` framework) login banners on linux machines.]]]
| https://github.com/JonasPammer/ansible-role-motd/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-motd/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-motd/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-motd/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-motd/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-motd/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59011%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59011%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-motd/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-motd[issues]]
| https://github.com/JonasPammer/ansible-role-motd/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-motd[pull requests]]

| https://github.com/JonasPammer/ansible-role-apache2[apache2] +
https://galaxy.ansible.com/jonaspammer/apache2[image:https://img.shields.io/badge/galaxy-jonaspammer.apache2-blueviolet[Available on Galaxy,title=pass:[An ansible role for installing Apache2, enabling/disabling modules, configuring its defaults and creating virtual hosts. Based on geerlingguy&#39;s apache2 role. ]]]
| https://github.com/JonasPammer/ansible-role-apache2/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-apache2/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-apache2/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-apache2/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-apache2/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-apache2/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59475%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59475%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-apache2/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-apache2[issues]]
| https://github.com/JonasPammer/ansible-role-apache2/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-apache2[pull requests]]

| https://github.com/JonasPammer/ansible-role-openssl[openssl] +
https://galaxy.ansible.com/jonaspammer/openssl[image:https://img.shields.io/badge/galaxy-jonaspammer.openssl-blueviolet[Available on Galaxy,title=pass:[An ansible role for generating OpenSSL Certificate Files.]]]
| https://github.com/JonasPammer/ansible-role-openssl/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-openssl/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-openssl/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-openssl/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-openssl/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-openssl/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59584%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59584%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-openssl/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-openssl[issues]]
| https://github.com/JonasPammer/ansible-role-openssl/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-openssl[pull requests]]

| https://github.com/JonasPammer/ansible-role-goaccess[goaccess] +
https://galaxy.ansible.com/jonaspammer/goaccess[image:https://img.shields.io/badge/galaxy-jonaspammer.goaccess-blueviolet[Available on Galaxy,title=pass:[An ansible role for installing GoAccess, a real-time web log analyzer that runs in a terminal or the browser.]]]
| https://github.com/JonasPammer/ansible-role-goaccess/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-goaccess/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-goaccess/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-goaccess/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-goaccess/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-goaccess/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59615%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F59615%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-goaccess/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-goaccess[issues]]
| https://github.com/JonasPammer/ansible-role-goaccess/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-goaccess[pull requests]]

| https://github.com/JonasPammer/ansible-role-mediawiki[mediawiki] +
https://galaxy.ansible.com/jonaspammer/mediawiki[image:https://img.shields.io/badge/galaxy-jonaspammer.mediawiki-blueviolet[Available on Galaxy,title=pass:[An ansible role for downloading mediawiki into specified directory, installing recommended system packages and downloading additional extensions and skins.]]]
| https://github.com/JonasPammer/ansible-role-mediawiki/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-mediawiki/actions/workflows/ci.yml/badge.svg[Testing CI]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-mediawiki/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-mediawiki/master.svg[pre-commit.ci status]]
| https://github.com/JonasPammer/ansible-role-mediawiki/releases[image:https://img.shields.io/github/commits-since/JonasPammer/ansible-role-mediawiki/latest.svg[version]]
// image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=latest%20version%20on%20galaxy&query=%24.summary_fields.versions%5B0%5D.name&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F0%2F%3Fformat%3Djson[Latest Version on Ansible Galaxy]
image:https://img.shields.io/badge/dynamic/json?color=blueviolet&label=galaxy%20downloads&query=%24.download_count&url=https%3A%2F%2Fgalaxy.ansible.com%2Fapi%2Fv1%2Froles%2F0%2F%3Fformat%3Djson[Downloads Count as per Ansible Galaxy]
| https://github.com/JonasPammer/ansible-role-mediawiki/issues[image:https://img.shields.io/github/issues-raw/JonasPammer/ansible-role-mediawiki[issues]]
| https://github.com/JonasPammer/ansible-role-mediawiki/pulls[image:https://img.shields.io/github/issues-pr/JonasPammer/ansible-role-mediawiki[pull requests]]

|===

=== Dependencies

==== Soft Dependencies
Most roles have a set of “soft dependencies” described in their `requirements.yml` file.
These soft dependencies are used in the relevant CI Tests
to prepare the machine for the execution of a given role
or to test some kind of interoperability.

You can choose to use those roles if you like them.

Here is an overview of all roles with their soft dependencies:

image:./graphs/dependencies_ALL.svg[requriements.yml soft-dependency graph of all roles]

The dependencies are soft for these reasons:

* Better re-usability.
* Easier to fork.
* *Lets the system developer assume a start-state of a machine.*

Because these dependencies are loose,
you have to include them in your playbook yourself
(assuming you want to use them):

[source,yaml]
----
- name: make the best machine ever
  hosts: all
  become: true

  roles:
    - name: jonaspammer.bootstrap
    - name: jonaspammer.java
----

==== Hard Dependencies

Some roles have a required hard dependency on another role,
mainly for a common handler or for variables that are set in the parent role and used in the child role.
_These role dependencies
(https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#using-role-dependencies[official documentation])
are described in `meta/main.yml` file of a given role under `dependencies`._

|===
| Role name | Depends on | Reason














































|===

Here is an overview of all hard dependencies:

image:./graphs/dependencies_ALL-hard.svg[meta/main.yml hard-dependency graph of all roles]

Because Ansible defines role dependencies as 'prerequisites' and not 'true dependencies',
you still *have to* include them in your playbook yourself:

[source,yaml]
----
- name: Converge
  hosts: all
  become: true

  roles:
    # (preperation roles have been left out for this example)

    - name: jonaspammer.httpd
    - name: jonaspammer.php
----


=== Tested Distributions

A role may work on different *distributions*, like Red Hat Enterprise Linux (RHEL),
even though there is no test for this exact distribution.

The following Linux distributions are included in the tests of most roles
https://github.com/JonasPammer/cookiecutter-ansible-role/blob/master/ansible-role-%7B%7B%20cookiecutter.role_name%20%7D%7D/.github/workflows/ci.yml[by default]:

|===
| OS Family | Distribution | Distribution Release Date | Distribution End of Life | Accompanying Docker Image

| RedHat
| CentOS 7
| 2014-07
| 2024-06
| https://github.com/geerlingguy/docker-centos7-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-centos7-ansible/workflows/Build/badge.svg?branch=master[CI]]
(https://github.com/geerlingguy/docker-centos7-ansible/issues/18[*,title="CentOS 7 is old"])

| Rocky
| Rocky Linux 8 (https://www.howtogeek.com/devops/is-rocky-linux-the-new-centos/[RHEL/CentOS 8 in disguise])
| 2021-06
| 2029-05
| https://github.com/geerlingguy/docker-rockylinux8-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-rockylinux8-ansible/workflows/Build/badge.svg?branch=master[CI]]

| RedHat
| Fedora 35
| 2021-11
| 2022-11
| https://github.com/geerlingguy/docker-fedora35-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-fedora35-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Ubuntu 1604
| 2016-04
| 2026-04
| https://github.com/geerlingguy/docker-ubuntu1604-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu1604-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Ubuntu 1804
| 2018-04
| 2028-04
| https://github.com/geerlingguy/docker-ubuntu1804-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu1804-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Ubuntu 2004
| 2021-09
| 2030-04
| https://github.com/geerlingguy/docker-ubuntu2004-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu2004-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Debian 10
| 2019-07
| 2022-08
| https://github.com/geerlingguy/docker-debian10-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian10-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Debian 11
| 2021-08
| ?
| https://github.com/geerlingguy/docker-debian11-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian11-ansible/workflows/Build/badge.svg?branch=master[CI]]
|===

=== Tested Ansible versions

The following Ansible versions are tested in the tests of each distribution
https://github.com/JonasPammer/cookiecutter-ansible-role/blob/master/ansible-role-%7B%7B%20cookiecutter.role_name%20%7D%7D/tox.ini[by default]:

* 2.11 (Ansible 4)
* 2.12 (Ansible 5)

This is equivalent with the
https://github.com/ansible-collections/community.general#tested-with-ansible[
support pattern of Ansible's `community.general` collection].