#!/usr/bin/env bash
function echo_err() {
    echo -e "\e[41m ${*} \e[49m"
}
function echo_meh() {
    echo -e "\e[103m ${*} \e[49m"
}
pwd=$(pwd)

if ! command -v gh &> /dev/null; then
    echo_err "'gh' command could not be found"
    exit 1
fi

stty -echo
echo -n "Please enter the GALAXY_API_KEY secret to be applied to all ansible-role's:"
read secret_input
stty echo
echo

for d in ./all-repos/ansible-role-*; do
    cd "$pwd"
    cd "$d"

    gh secret set GALAXY_API_KEY --body "${secret_input}" --repos "$d"
done